export const MAP_DIMENSIONS = {
  WEST_START: 56,
  WEST_END: 20,
  SOUTH_START: 12,
  SOUTH_END: 50,
};

export const GRID = {
  COLS: MAP_DIMENSIONS.WEST_START - MAP_DIMENSIONS.WEST_END + 1, // 37
  ROWS: MAP_DIMENSIONS.SOUTH_END - MAP_DIMENSIONS.SOUTH_START + 1, // 39
};
